/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package faizinputan;

import java.awt.event.ItemEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ButtonGroup;

/**
 *
 * @author faiz
 */
public class Input extends javax.swing.JFrame {

    /**
     * Creates new form Input
     */
    public Input() {
        initComponents();
        aktif();
        JenKel.add(rbLk);
        JenKel.add(rbLp);
        this.rbLk.setActionCommand("Laki - Laki");
        this.rbLp.setActionCommand("Perempuan");
        Hobby.add(cbRenang);
        Hobby.add(cbBasket);
        Hobby.add(cbFutsal);
        this.cbRenang.setActionCommand("Renang");
        this.cbBasket.setActionCommand("Basket");
        this.cbFutsal.setActionCommand("Basket");

    }
    String kel, hb;
    private final ButtonGroup JenKel = new ButtonGroup();
    private final ButtonGroup Hobby = new ButtonGroup();

    protected void aktif() {
        txt1.setEnabled(false);
        txt2.setEnabled(false);
        txt3.setEnabled(false);
        rbLp.setEnabled(true);
        rbLk.setEnabled(true);
        cbRenang.setEnabled(true);
        cbBasket.setEnabled(true);
        cbFutsal.setEnabled(true);
        cbAgama.setSelectedIndex(0);
        Hobi();
        agama();
        kelamin();
    }

    public void Hobi() {
        cbRenang.addItemListener((ItemEvent event) -> {
            if (event.getSource() == cbRenang) {
                if (event.getStateChange() == ItemEvent.SELECTED) {
                    txtHobby.setText("Renang");
                    cbRenang.setSelected(false);
                }
            }
        });
        cbBasket.addItemListener((ItemEvent event) -> {
            if (event.getSource() == cbBasket) {
                if (event.getStateChange() == ItemEvent.SELECTED) {
                    txtHobby.setText("Basket");
                    cbBasket.setSelected(false);
                }
            }
        });
        cbFutsal.addItemListener((ItemEvent event) -> {
            if (event.getSource() == cbFutsal) {
                if (event.getStateChange() == ItemEvent.SELECTED) {
                    txtHobby.setText("Futsal");
                    cbFutsal.setSelected(false);
                }
            }
        });
    }

    public void agama() {
        cbAgama.addItemListener((ItemEvent e) -> {
            if (e.getStateChange() == ItemEvent.SELECTED) {
                if (cbAgama.getSelectedIndex() == 0) {
                    txtAgama.setText("Islam");
                } else if (cbAgama.getSelectedIndex() == 1) {
                    txtAgama.setText("Kristen");
                } else if (cbAgama.getSelectedIndex() == 2) {
                    txtAgama.setText("Katholik");
                } else if (cbAgama.getSelectedIndex() == 3) {
                    txtAgama.setText("Hindu");
                } else if (cbAgama.getSelectedIndex() == 4) {
                    txtAgama.setText("Budha");
                }
            }
        });
    }

    public void kelamin() {
        rbLk.addItemListener((ItemEvent event) -> {
            if (event.getSource() == rbLk) {
                if (event.getStateChange() == ItemEvent.SELECTED) {
                    txtNama.setText("Laki-Laki");
                }
            }
        });
        rbLp.addItemListener((ItemEvent event) -> {
            if (event.getSource() == rbLp) {
                if (event.getStateChange() == ItemEvent.SELECTED) {
                    txtNama.setText("Perempuan");
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rbLk = new javax.swing.JRadioButton();
        rbLp = new javax.swing.JRadioButton();
        txtNama = new javax.swing.JTextField();
        cbRenang = new javax.swing.JCheckBox();
        cbBasket = new javax.swing.JCheckBox();
        Hbby = new javax.swing.JLabel();
        txtHobby = new javax.swing.JTextField();
        Agama = new javax.swing.JLabel();
        cbAgama = new javax.swing.JComboBox<>();
        txtAgama = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        txtWarna = new javax.swing.JLabel();
        cbFutsal = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("INPUT");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Jenis Kelamin");

        rbLk.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rbLk.setText("Laki - Laki");
        rbLk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLkActionPerformed(evt);
            }
        });

        rbLp.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rbLp.setText("Perempuan");
        rbLp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLpActionPerformed(evt);
            }
        });

        cbRenang.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cbRenang.setText("Renang");
        cbRenang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRenangActionPerformed(evt);
            }
        });

        cbBasket.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cbBasket.setText("Basket");
        cbBasket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBasketActionPerformed(evt);
            }
        });

        Hbby.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Hbby.setText("Hobby");

        Agama.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Agama.setText("Agama");

        cbAgama.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cbAgama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Kristen", "Katholik", "Hindu", "Budha", " " }));
        cbAgama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAgamaActionPerformed(evt);
            }
        });

        txt1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txt1.setText("Merah");
        txt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt1MouseClicked(evt);
            }
        });

        txt2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txt2.setText("Kuning");
        txt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt2MouseClicked(evt);
            }
        });
        txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2ActionPerformed(evt);
            }
        });

        txt3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txt3.setText("Hijau");
        txt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt3MouseClicked(evt);
            }
        });

        txtWarna.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N

        cbFutsal.setText("Ftusal");
        cbFutsal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFutsalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(306, 306, 306)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(195, 195, 195)
                                .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(166, 166, 166)
                                .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(245, 245, 245)
                                .addComponent(txtWarna, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 87, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(Hbby))
                                        .addGap(73, 73, 73)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbAgama, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cbRenang)
                                                    .addComponent(rbLk))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(rbLp)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(cbBasket)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(cbFutsal))))))
                                    .addComponent(Agama))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNama)
                                    .addComponent(txtHobby)
                                    .addComponent(txtAgama, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)))
                            .addComponent(jSeparator1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rbLk)
                    .addComponent(rbLp)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbRenang)
                    .addComponent(cbBasket)
                    .addComponent(Hbby)
                    .addComponent(txtHobby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFutsal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Agama)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(txtWarna, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbLkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLkActionPerformed
        kel = rbLk.getText();
        kelamin();// TODO add your handling code here:
    }//GEN-LAST:event_rbLkActionPerformed

    private void rbLpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLpActionPerformed
        kel = rbLp.getText();
        kelamin();// TODO add your handling code here:
    }//GEN-LAST:event_rbLpActionPerformed

    private void cbRenangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRenangActionPerformed
        hb = cbRenang.getText();
        Hobi(); // TODO add your handling code here:
    }//GEN-LAST:event_cbRenangActionPerformed

    private void cbBasketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBasketActionPerformed
        hb = cbBasket.getText();
        Hobi();   // TODO add your handling code here:
    }//GEN-LAST:event_cbBasketActionPerformed

    private void cbAgamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAgamaActionPerformed
        agama();        // TODO add your handling code here:
    }//GEN-LAST:event_cbAgamaActionPerformed

    private void txt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt1MouseClicked
        txt1.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                txtWarna.setText(txt1.getText());
            }
        });        // TODO add your handling code here:
    }//GEN-LAST:event_txt1MouseClicked

    private void txt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt2MouseClicked
        txt2.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                txtWarna.setText(txt2.getText());
            }
        });          // TODO add your handling code here:
    }//GEN-LAST:event_txt2MouseClicked

    private void txt3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt3MouseClicked
        txt3.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                txtWarna.setText(txt3.getText());
            }
        });          // TODO add your handling code here:
    }//GEN-LAST:event_txt3MouseClicked

    private void txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2ActionPerformed

    private void cbFutsalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFutsalActionPerformed
        hb = cbFutsal.getText();
        Hobi(); // TODO add your handling code here:
    }//GEN-LAST:event_cbFutsalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Input().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Agama;
    private javax.swing.JLabel Hbby;
    private javax.swing.JComboBox<String> cbAgama;
    private javax.swing.JCheckBox cbBasket;
    private javax.swing.JCheckBox cbFutsal;
    private javax.swing.JCheckBox cbRenang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbLk;
    private javax.swing.JRadioButton rbLp;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txtAgama;
    private javax.swing.JTextField txtHobby;
    private javax.swing.JTextField txtNama;
    private javax.swing.JLabel txtWarna;
    // End of variables declaration//GEN-END:variables
}
